# - Variaveis de teste - #
@meuHospital = 456ab755-3e62-4566-87ca-4e6cb87ecbd4
@usuarioThiago = f45e30a8-e2c6-4e9f-bbc0-e6f03bc7d34c
@setorUtiAdulto = b27fbd9e-a90e-4089-a521-8c283d0c8d76

@indicadorTaxaOcupacao = 35bf276e-2a42-4b75-86b6-356feb0d4664

@indicadorTxOcupaUTIAdulto = 4d669717-7d08-49df-b667-887cc1308a26

@variavelTxOcupacaoUTIAdulto = 2e58e795-ab13-4156-a060-1e3dbc6003e5

### 1. Criar um novo Hospital
POST http://localhost:3000/hospitais
Content-Type: application/json

{
  "nome": "Samaritano Barra",
  "cnpj": "11111111000111"
}

###

### 2. Criar novo usuário
POST http://localhost:3000/usuarios
Content-Type: application/json

{
  "nome": "Fernanda Figueiredo Doria",
  "email": "fernandafigueiredo@gmail.com",
  "password": "123456",
  "hospitalId": "{{meuHospital}}"
}

###

### 3. Criar um novo Setor
POST http://localhost:3000/setores
Content-Type: application/json

{
  "nome": "Maternidade",
  "hospitalId": "{{meuHospital}}"
}

###

### 4. Criar um novo Indicador (Geral)
POST http://localhost:3000/indicadores
Content-Type: application/json

{
  "nome": "Taxa de cesareanias",
  "descricao": "Porcentagem de cesareanias realizadas em relação ao total de partos.",
  "multiplicador": 100,
  "direcaoMeta": "MENOR_MELHOR",
  "hospitalId": "{{meuHospital}}"
}

###

### 5. Criar indicador para o Setor
POST http://localhost:3000/indicadores-setores
Content-Type: application/json

{
  "metaSetor": 20,
  "setorId": "{{setorUtiAdulto}}",
  "indicadorId": "{{indicadorTaxaOcupacao}}",
  "hospitalId": "{{meuHospital}}"
}

### 6. Registrar evento (Valor do Numerador)

POST http://localhost:3000/registros
Content-Type: application/json

{
  "quantidade": 15,
  "dataEvento": "2026-04-19",
  "responsavelId": "{{usuarioThiago}}",
  "justificativa": "Justificativa para o registro",
  "setorId": "{{setorUtiAdulto}}",
  "indicadorId": "{{indicadorTaxaOcupacao}}",
  "hospitalId": "{{meuHospital}}"
}

### 7. Registrar a variável operacional (Valor do Denominador)s
POST http://localhost:3000/variaveis
Content-Type: application/json

{
  "nome": "Taxa de cesarianias",
  "valor": 100,
  "hospitalId": "{{meuHospital}}",
  "mes": "2026-04",
  "setorId": "{{setorUtiAdulto}}"
}

### 8. Calcular Performance Mensal do Setor
GET http://localhost:3000/performance?hospitalId={{meuHospital}}&setorId={{setorUtiAdulto}}&indicadorId={{indicadorTaxaOcupacao}}&mes=2026-04