# - Variaveis de teste - #
@meuHospital = c8668a10-3386-4681-9933-3464d123bf8a
@usuarioFernanda = d5dd92b8-2453-4005-ad16-1c18e945c7d2
@setorUtiAdulto = 5351b43b-3379-4996-b547-ca8035a4c2b0

@indicadorTxIPCS = 2a1fffd1-282b-42f1-b2a2-ffbf0f090579

@metaSetorTxIPCS = f9fb8963-10a1-4a6b-a7a7-f5b3c3378c0f

@variavelTxIPCS = 762875c8-227b-48ef-8ced-d9870341c459

### 1. Criar um novo Hospital
POST http://localhost:3000/hospitais
Content-Type: application/json

{
  "nome": "Samaritano Botafogo",
  "cnpj": "00000000000002"
}

###

### 2. Criar novo usuário
POST http://localhost:3000/usuarios
Content-Type: application/json

{
  "nome": "Thiago Doria",
  "email": "thiagodoria@gmail.com",
  "password": "123456",
  "hospitalId": "c8668a10-3386-4681-9933-3464d123bf8a"
}

###

### 3. Criar um novo Setor
POST http://localhost:3000/setores
Content-Type: application/json

{
  "nome": "UTI pediátrica",
  "hospitalId": "40dd48d4-ea24-4c35-baa0-18cbaf2f5c46"
}

###

### 4. Criar um novo Indicador (Geral)
POST http://localhost:3000/indicadores
Content-Type: application/json

{
  "nome": "Taxa de IPCS",
  "descricao": "Percentual de infecções no setor",
  "multiplicador": 1000,
  "direcaoMeta": "MENOR_MELHOR",
  "hospitalId": "{{meuHospital}}"
}

###

### 5. Criar indicador para o Setor
POST http://localhost:3000/indicadores-setores
Content-Type: application/json

{
  "metaSetor": 0.0,
  "setorId": "4ba2da8f-6ca9-4f2b-98ba-9c05aeb2fee0",
  "indicadorId": "{{indicadorTxIPCS}}"
}

### 6. Registrar evento (Valor do Numerador)

POST http://localhost:3000/registros
Content-Type: application/json

{
  "quantidade":2,
  "dataEvento": "2026-03-19",
  "responsavelId": "73a117f6-d3f1-46ed-9fdc-2da0f44ccbb9",
  "justificativa": "Justificativa para o registro",
  "setorId": "4ba2da8f-6ca9-4f2b-98ba-9c05aeb2fee0",
  "indicadorId": "{{indicadorTxIPCS}}",
  "hospitalId": "40dd48d4-ea24-4c35-baa0-18cbaf2f5c46"
}

### 7. Registrar a variável operacional (Valor do Denominador)s
POST http://localhost:3000/variaveis
Content-Type: application/json

{
  "nome": "Taxa de IPCS",
  "valor": 100,
  "hospitalId": "40dd48d4-ea24-4c35-baa0-18cbaf2f5c46",
  "mes": "2026-04",
  "setorId": "4ba2da8f-6ca9-4f2b-98ba-9c05aeb2fee0"
}

### 8. Calcular Performance Mensal do Setor
GET http://localhost:3000/performance?hospitalId=40dd48d4-ea24-4c35-baa0-18cbaf2f5c46&setorId=4ba2da8f-6ca9-4f2b-98ba-9c05aeb2fee0&indicadorId={{indicadorTxIPCS}}&mes=2026-04